add_annotations: /fast/work/projects/genome-writing-qc/2021-08-09_Vinzenz_MidSox9_rerun/INPUT/features_on_ref.bed
alleles:
- /fast/work/projects/genome-writing-qc/2021-08-09_Vinzenz_MidSox9_rerun/INPUT/construct_rnd.bed
fastas:
- /fast/work/projects/genome-writing-qc/2021-08-09_Vinzenz_MidSox9_rerun/INPUT/sequences.fasta
reference: /fast/work/projects/genome-writing-qc/REF/mm10.chr11.fa
workdir: /fast/work/projects/genome-writing-qc/2021-08-09_Vinzenz_MidSox9_rerun
