add_annotations: /home/memsonmi/DEV/atlatl/tests/data/input/annotations.bed
alleles:
- /home/memsonmi/DEV/atlatl/tests/data/input/construct.bed
fastas:
- /home/memsonmi/DEV/atlatl/tests/data/input/sequences.fasta
reference: /home/memsonmi/DEV/atlatl/tests/data/input/ref.fasta
workdir: /home/memsonmi/DEV/atlatl/tests/data
